name             "main"
maintainer       "Matt Bridges"
maintainer_email "mbridges.91@gmail.com"
license          "Apache 2.0"
description      "Macbook Pro setup for Matt Bridges"
version          "0.0.1"
recipe           "main", "Setup my Macbook"
supports         "mac_os_x"
